version: "3"

services:
  laravel_db:
    container_name: laravel_db
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=laravel_user
      - POSTGRES_DB=laravel_db
    volumes:
      - ./docker/db:/var/lib/postgresql/data

  laravel_server:
    container_name: laravel_server
    depends_on:
      - laravel_db
    build: ./docker/laravel
    volumes:
      - ./laravel:/var/www/html/laravel
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=laravel_db
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=password
    ports:
      - 8000:8000
